language: python
python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
install:
  - sudo apt-get install python-daemon
  - python setup.py install
  - sudo apt-get remove python-daemon
# command to run tests
script: nosetests
