language: python
sudo: required
python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
addons:
  apt:
    packages:
    - mosquitto
install:
  - make travis-deps
  - python setup.py install
# command to run tests
script: 
 - nosetests --verbosity=2 --cover-min-percentage= --with-coverage
